HW2_A_SangMinPark: main.o input.o calc.o output.o linkedlist.o
	gcc -o HW2_A_SangMinPark main.c input.c calc.c output.c linkedlist.o
main.o: header.h main.c
	gcc -c main.c
input.o: header.h input.c
	gcc -c input.c
calc.o: header.h calc.c
	gcc -c calc.c
output.o: header.h output.c
	gcc -c output.c
linkedlist.o: header.h linkedlist.c
	gcc -c linkedlist.c
	
