HW2_A_SangMinPark: main.o input.o calc.o output.o
	gcc -o HW2_A_SangMinPark main.o input.o calc.o output.o
main.o: main.c
	gcc -c main.c
input.o: input.c
	gcc -c input.c
calc.o: calc.c
	gcc -c calc.c
output.o: output.c
	gcc -c output.c
